### ISSUE TITLE
Not waiting for an app to finish

### ISSUE THREAD

**Issue by FreeHarry** [kiennq/scoop-better-shimexe#14]
This is an issue with shim `kiennq` in scoop 0.5.2
I have `WinMerge` (GUI) installed with `scoop` and use the shim `WinMergeU.exe` in my `.gitconfig` as difftool:

```properties
# Git config
[difftool "winmerge"]
    name = WinMerge
    cmd = "WinMergeU.exe" -u -e -r $LOCAL $REMOTE
```

When I run, e.g `git difftool -d HEAD`, then `Git` is **NOT waiting** for WinMerge to close the diff and the temp-files generated by git are removed immediately . So diff will not work.

The same happens with Notepad++, set as editor in `.gitconfig`:

```properties
# Git config
[core]
	editor = "notepad++.exe" -multiInst -notabbar -nosession
	autocrlf = input
```
 So when I run e.g. `git commit`, then `Git` is **NOT waiting** for Notepad++ to close.

I have this issue only with shim `kiennq`. When I use the shim `default`, I don't have this problem, neither if I use the explicit app-path to WinMerge.

Is this behavior of  `kiennq` intended?

**Comment by kiennq** [comment]
It was intended before (I can seem to remember why) but the idea is the Windows app can be detached immediately without waiting for it to finish.
Can you try with this version https://github.com/kiennq/scoop-better-shimexe/releases/tag/v3.1.1.1e9d6fc to see if your issue is resolved?

**Comment by FreeHarry** [comment]
I checked it and it is working correctly now. Thanks!
