### ISSUE TITLE
CLI shim regression from `2.2.1`

### ISSUE THREAD

**Issue by brian6932** [kiennq/scoop-better-shimexe#9]
https://github.com/ScoopInstaller/Scoop/issues/1606#issuecomment-2016887486
> https://github.com/ScoopInstaller/Scoop/commit/5153d7375bb932807f77f03f739a03b385ac9542 seems to break this for me
>```pwsh
>❯ streamlink
>
>❯ & (scoop which streamlink)
>usage: streamlink [OPTIONS] <URL> [STREAM]
>
>Use -h/--help to see the available options or read the manual at https://streamlink.github.io
>```
>manifests reproduced/tested on
>https://github.com/brian6932/dank-scoop/blob/master/bucket/streamlink-nightly-lean-ttv-lol.json
>https://github.com/brian6932/dank-scoop/blob/master/bucket/streamlink-nightly-lean.json

https://github.com/kiennq/scoop-better-shimexe/compare/2.2.1...v3.1

**Comment by kiennq** [comment]
Should be fixed in the new version.
